# Metrics specs
metrics:
  # List of connection urls
  # Template url: postgresql://username:password@host:port/dbname[?paramspec]
  # You might want to create password file, see: https://www.postgresql.org/docs/14/libpq-pgpass.html
  databases:
    - name: node1
      url: postgresql://monitoring:1234@192.168.31.144:5411/mydb?sslmode=disable

  # Port that server will listen on for incoming connections
  # Default: 8080
  listenPort: 8080

  # Interval between gathering metrics
  # Default: 10
  interval: 10

  # Query timeout in seconds
  # Default: 5
  queryTimeout: 5

  # Connections per database
  # Default: 5
  connectionPoolMaxSize: 5

