apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mtm-metrics
  labels:
    app: mtm-metrics
    release: prometheus
spec:
  podMetricsEndpoints:
    - interval: 10s
      port: metrics
  selector:
    matchLabels:
      app: mtm-metrics