apiVersion: v1
kind: ConfigMap
metadata:
  name: mtm-metrics-config
data:
  config.yaml: |-
    metrics:
      databases:
        - name: node1
          url: postgresql://user:1234@node0:5432/demo?sslmode=disable
      listenPort: 8080
      interval: 5
      queryTimeout: 4
      connectionPoolMaxSize: 5
