{
 "title": "Instances Compare",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "conn",
    "label": "Connection",
    "query": {
     "query": "label_values(postgresql_up, connection_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$conn - Connections by state",
   "type": "timeseries",
   "description": "Most of multimaster processes have null state",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "repeat": "conn",
   "targets": [
    {
     "expr": "sum by (state) (postgresql_backends_by_state_total{connection_name=~\"$conn\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Tuples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$conn - All activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "repeat": "conn",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (stat) (rate(postgresql_database_reading_usage{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{stat}}"
    },
    {
     "expr": "sum by (stat) (rate(postgresql_database_writing_usage{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  {
   "title": "$conn - Reading activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "repeat": "conn",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (stat) (rate(postgresql_database_reading_usage{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  {
   "title": "$conn - Writing activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "repeat": "conn",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (stat) (rate(postgresql_database_writing_usage{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "$conn - Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "repeat": "conn",
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_transactions_commit_sum{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum by (connection_name) (rate(postgresql_transactions_rollback_sum{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "Rollbacks"
    }
   ]
  }
 ]
}