{
 "title": "Instances Overview",
 "tags": [ "multimaster" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "conn",
    "label": "Connection",
    "query": {
     "query": "label_values(postgresql_up, connection_name)"
    }
   },
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Info",
   "type": "table",
   "description": "Shows most recent info about nodes.\n\nLatency is RTT between Postgres instance and metrics exporter",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mtm_status{connection_name=~\"$conn\"} == 1 ",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "mtm_gen_num{connection_name=~\"$conn\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "postgresql_latency{connection_name=~\"$conn\"}",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "postgresql_backends_total{connection_name=~\"$conn\"}",
     "legendFormat": "Backends"
    }
   ]
  },
  {
   "title": "Nodes count",
   "type": "stat",
   "description": "Number of monitored nodes",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (group by (connection_name) (postgresql_up{connection_name=~\"$conn\"}))"
    }
   ]
  },
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "description": "Status map of every node in multimaster cluster.\n\nIf bucket contains several statuses then the one with the higher priority will be showed. Priority is showed at the bottom, left to right",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "(max_over_time(mtm_status{connection_name=~\"$conn\", status=\"online\"}[$__interval]) == 1) * 1",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "(max_over_time(mtm_status{connection_name=~\"$conn\", status=\"recovery\"}[$__interval]) == 1) * 2",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "(max_over_time(mtm_status{connection_name=~\"$conn\", status=\"catchup\"}[$__interval]) == 1) * 3",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "(max_over_time(mtm_status{connection_name=~\"$conn\", status=\"disabled\"}[$__interval]) == 1) * 4",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "(max_over_time(mtm_status{connection_name=~\"$conn\", status=\"isolated\"}[$__interval]) == 1) * 5",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "(min_over_time(postgresql_up{connection_name=~\"$conn\"}[$__interval]) == 0)",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  { "title": "Replication lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Replication lag",
   "type": "timeseries",
   "description": "Replication lag shows how nodes lag between each other.\n\nFor example, `node1 mtm_slot_2` shows how much data has accumulated in the `node1`'s slot for `node2`",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (connection_name, slot_name) (rate(postgresql_replication_lag_bytes{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}} {{slot_name}}"
    }
   ]
  },
  { "title": "Tuples details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Fetched",
   "type": "timeseries",
   "description": "Number of live rows fetched by index scans in this database. See `pg_stat_database`\n\nTable `t` with 1000 rows: \\\n`SELECT count(*) FROM t;`\n\nFetched: 1 \\\nReturned: 1000",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_database_reading_usage{connection_name=~\"$conn\", stat=\"tup_fetched\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Returned",
   "type": "timeseries",
   "description": "Number of live rows fetched by sequential scans and index entries returned by index scans in this database.  See `pg_stat_database`\n\nTable `t` with 1000 rows: \\\n`SELECT count(*) FROM t;`\n\nFetched: 1 \\\nReturned: 1000",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_database_reading_usage{connection_name=~\"$conn\", stat=\"tup_returned\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Inserted",
   "type": "timeseries",
   "description": "Number of rows inserted by queries in this database. See `pg_stat_database`",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_database_writing_usage{connection_name=~\"$conn\", stat=\"tup_inserted\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "timeseries",
   "description": "Number of rows updated by queries in this database. See `pg_stat_database`",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_database_writing_usage{connection_name=~\"$conn\", stat=\"tup_updated\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "timeseries",
   "description": "Number of rows deleted by queries in this database. See `pg_stat_database`",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_database_writing_usage{connection_name=~\"$conn\", stat=\"tup_deleted\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "description": "Disc space used by the database. See `pg_database_size`\n\nIt may diverge over time cause some data is not replicated to other nodes",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (connection_name) (postgresql_size_bytes{connection_name=~\"$conn\"})",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  { "title": "Connection details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "By state",
   "type": "timeseries",
   "description": "Most of multimaster processes have null state",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (state) (postgresql_backends_by_state_total{connection_name=~\"$conn\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "By user",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by (user) (postgresql_backends_by_user_total{connection_name=~\"$conn\"})",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_transactions_sum{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name }}"
    }
   ]
  },
  {
   "title": "Commits per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_transactions_commit_sum{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name }}"
    }
   ]
  },
  {
   "title": "Rollbacks per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_transactions_rollback_sum{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name }}"
    }
   ]
  }
 ]
}