{
 "title": "Nodes",
 "tags": [ "multimaster" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "conn",
    "label": "Conn",
    "query": {
     "query": "label_values(postgresql_up, connection_name)"
    }
   },
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mtm_status{connection_name=~\"$conn\"} == 1 ",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "mtm_gen_num{connection_name=~\"$conn\"}[$__range]",
     "legendFormat": "__auto"
    },
    {
     "expr": "postgresql_latency{connection_name=~\"$conn\"}",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "postgresql_backends_total{connection_name=~\"$conn\"}",
     "legendFormat": "Backends"
    }
   ]
  },
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "(max_over_time(mtm_status{connection_name=~\"$conn\", status=\"online\"}[$__interval]) == 1) * 1",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "(max_over_time(mtm_status{connection_name=~\"$conn\", status=\"recovery\"}[$__interval]) == 1) * 2",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "(max_over_time(mtm_status{connection_name=~\"$conn\", status=\"catchup\"}[$__interval]) == 1) * 3",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "(max_over_time(mtm_status{connection_name=~\"$conn\", status=\"disabled\"}[$__interval]) == 1) * 4",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "(max_over_time(mtm_status{connection_name=~\"$conn\", status=\"isolated\"}[$__interval]) == 1) * 5",
     "legendFormat": "{{connection_name}}"
    },
    {
     "expr": "(min_over_time(postgresql_up{connection_name=~\"$conn\"}[$__interval]) == 0)",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  { "title": "DB Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Fetched",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_database_reading_usage{connection_name=~\"$conn\", stat=\"tup_fetched\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Returned",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_database_reading_usage{connection_name=~\"$conn\", stat=\"tup_returned\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Inserted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_database_writing_usage{connection_name=~\"$conn\", stat=\"tup_inserted\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_database_writing_usage{connection_name=~\"$conn\", stat=\"tup_updated\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_database_writing_usage{connection_name=~\"$conn\", stat=\"tup_deleted\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (connection_name) (postgresql_size_bytes{connection_name=~\"$conn\"})",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  { "title": "Backends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "By state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (state) (postgresql_backends_by_state_total{connection_name=~\"$conn\"})",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "By user",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (user) (postgresql_backends_by_user_total{connection_name=~\"$conn\"})",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_transactions_sum{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name }}"
    }
   ]
  },
  {
   "title": "Commits per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 31 },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_transactions_commit_sum{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name }}"
    }
   ]
  },
  {
   "title": "Rollbacks per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_transactions_rollback_sum{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name }}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (connection_name) (rate(postgresql_queries_sum{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "Slowest queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "postgresql_slowest_queries{connection_name=~\"$conn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Replication lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (connection_name,slot_name) (rate(postgresql_replication_lag_bytes{connection_name=~\"$conn\"}[$__rate_interval]))",
     "legendFormat": "{{connection_name}} {{slot_name}}"
    }
   ]
  }
 ]
}