apiVersion: v1
kind: Secret
metadata:
  name: mmts-toolbox-config
stringData:
  config.yaml: |-
    toolbox:
      connections:
        - name: node1
          ssh:
            user: user
            host: node1
            port: 22
            bastion:
              user: user
              host: node0
              port: 22
      pgdata: ./db
      pgbin: /usr/local/pgsql/bin
