version: "2.11"

services:
  mtm-1:
    image: ${IMAGE}
    entrypoint:
      - /bin/bash
      - ./scripts/entrypoint.sh
    networks:
      mtmnet:
        ipv4_address: $HOST1
  mtm-2:
    image: ${IMAGE}
    entrypoint:
      - /bin/bash
      - ./scripts/entrypoint.sh
    networks:
      mtmnet:
        ipv4_address: $HOST2
  mtm-3:
    image: ${IMAGE}
    entrypoint:
      - /bin/bash
      - ./scripts/entrypoint.sh
    networks:
      mtmnet:
        ipv4_address: $HOST3
networks:
  mtmnet:
    driver: bridge
    ipam:
      config:
        - subnet: $SUBNET1
