---
# Prepare nodes for postgres and multimaster
# Connecting to root
- name: Update systems and create user
  hosts: mm1,mm2
  tags: prepare
  tasks:
  - name: Install updates
    apt:
      upgrade: dist
      update_cache: yes

  - name: Install packages
    apt:
      name:
      - flex
      - bison
      - libreadline-dev
      - gcc
      - g++
      - clang
      - make
      - cmake
      - libipc-run-perl
  
  - name: Create postgres user
    user: 
      name: postgres
      shell: /bin/bash
      password: $6$FgLxeneHNpbe5Ugx$kTl14v2KF5NAW/f3cVK78iC4mh/mE.wpowZ/ygZ8PcALbUXQpEcd7asN2FLbn.JlZ5PjJN18TlyWRMMc/fr.F1 # 1234

  - name: Add postgres to sudoers
    shell: sudo usermod -aG sudo postgres

  - name: Copy hosts to nodes
    copy:
      src: hosts
      dest: /etc/hosts

  - name: Update PATH env var
    shell: |
      echo "export PATH=$PATH:/usr/local/pgsql/bin" | tee -a /etc/profile

# Build postgres and multimaster
- name: Prepare for multimasters
  hosts: mm1,mm2
  remote_user: postgres # Connecting to non-root
  tasks:
  - name: Clone modified postgres
    tags: pg,build
    git:
      repo: https://github.com/postgrespro/postgres_cluster.git
      dest: /home/postgres/postgres_cluster
      version: rel13_mm_2

  - name: Clone multimaster
    tags: mm,build
    git:
      repo: https://github.com/postgrespro/mmts.git
      dest: /home/postgres/postgres_cluster/contrib/mmts
      version: PGPRO-6254

  - name: Compile postgres
    tags: pg,build
    become: yes # We need root priveleges to build pg into /usr/local/
    shell: |
      ./configure
      make
      make install
    args:
      chdir: /home/postgres/postgres_cluster

  - name: Compile multimaster
    tags: mm,build
    become: yes # Same
    shell: make install
    args:
      chdir: /home/postgres/postgres_cluster/contrib/mmts

  - name: Compile pg_stat_statements
    tags: build
    become: yes # Same
    shell: make install
    args:
      chdir: /home/postgres/postgres_cluster/contrib/pg_stat_statements

  - name: Remove pgsql
    tags: rmpgsql
    become: yes # Same
    shell: rm -rf /usr/local/pgsql

# Configure and control pg
  - name: Create PGDATA
    tags: pgdata,install
    become: yes # Same
    shell: | 
      mkdir ./db
      chown postgres ./db

  - name: Init database
    tags: initdb,install
    shell: /usr/local/pgsql/bin/initdb -D ./db
    register: out

  - debug:
      msg: "{{out.stdout_lines}} {{out.stderr_lines}}"
    tags: initdb,install
  
  - name: Copy config files
    tags: copy,cfg,install
    copy:
      src: "{{ item }}"
      dest: ./db
      owner: postgres
    with_items:
      - pg_hba.conf
      - postgresql.conf
  
  - name: Copy pgpass
    tags: copy,pgpass,install
    copy:
      src: pgpass
      dest: /home/postgres/.pgpass
      owner: postgres
      mode: '0600'

  - name: Copy bootstrap.sql
    tags: copy,bootstrap,install
    copy:
      src: "{{ item }}"
      dest: /home/postgres/
      owner: postgres
    with_items:
      - bootstrap.sql

  - name: Start postgres
    tags: start,install
    shell: |
      rm logfile
      /usr/local/pgsql/bin/pg_ctl -D ./db -l ./db/logfile start
    register: out

  - debug: 
      msg: "{{out.stdout_lines}} {{out.stderr_lines}}"
    tags: start,install

  - name: Bootstrpap db
    tags: bootstrap,install
    shell: /usr/local/pgsql/bin/psql -f bootstrap.sql
    register: out

  - debug: 
      msg: "{{out.stdout_lines}} {{out.stderr_lines}}"
    tags: bootstrap,install
  
  - name: Stop postgres
    tags: stop,uninstall
    shell: /usr/local/pgsql/bin/pg_ctl -D ./db stop
    register: out

  - debug: 
      msg: "{{out.stdout_lines}} {{out.stderr_lines}}"
    tags: stop
 
  - name: Remove PGDATA
    tags: rmpgdata,uninstall
    become: yes # Same
    shell: rm -rf ./db

  - name: Status postgres
    tags: status
    shell: /usr/local/pgsql/bin/pg_ctl -D ./db status
    register: out

  - debug: 
      msg: "{{out.stdout_lines}} {{out.stderr_lines}}"
    tags: status
  
# Nodes that will init multimasters
- name: Init multimaster clusters
  hosts: init1, init2
  remote_user: postgres
  tags: clusters
  tasks:
  - name: Copy init files
    copy:
      src: "{{ mtm_file }}"
      dest: /home/postgres
    register: out

  - name: Init multimaster
    shell: /usr/local/pgsql/bin/psql -U mtmuser -d mydb -f {{ mtm_file }}
    register: out

  - debug:
      msg: "{{out.stdout_lines}} {{out.stderr_lines}}"

- name: Enable monitoring
  hosts: init1,init2
  remote_user: postgres
  tags: monitoring
  tasks:
  - name: Copy monitoring.sql
    copy:
      src: "{{ item }}"
      dest: /home/postgres/
      owner: postgres
    with_items:
      - monitoring.sql

  - name: Add monitoring
    shell: /usr/local/pgsql/bin/psql -U mtmuser -d mydb -f monitoring.sql
    register: out

  - debug:
      msg: "{{out.stdout_lines}} {{out.stderr_lines}}"

# Check statuses of mm clusters       
- name: Status multimasters 
  hosts: init1, init2
  remote_user: postgres
  tags: checkmm
  tasks:
  - name: Check multimasters
    shell: /usr/local/pgsql/bin/psql -U mtmuser -d mydb -c "SELECT * FROM mtm.status();"
    register: out

  - debug:
      msg: "{{out.stdout_lines}} {{out.stderr_lines}}"

  - name: Check nodes
    shell: /usr/local/pgsql/bin/psql -U mtmuser -d mydb -c "SELECT * FROM mtm.nodes();"
    register: out

  - debug:
      msg: "{{out.stdout_lines}} {{out.stderr_lines}}"
