apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmts-metrics-deployment
  labels:
    app: mmts-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmts-metrics
  template:
    metadata:
      labels:
        app: mmts-metrics
        prometheus.deckhouse.io/custom-target: mmts-metrics
      annotations:
        prometheus.deckhouse.io/port: "8080"
        prometheus.deckhouse.io/sample-limit: "5000"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: mmts-metrics
          image: borodun/mmts-metrics
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /home/mmts/config.yaml
              subPath: config.yaml
            - name: pgpass
              mountPath: /home/mmts/.pgpass
              subPath: .pgpass
              readOnly: true
            - name: hosts
              mountPath: /etc/hosts
              subPath: hosts
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: mmts-metrics-config
            optional: false
        - name: pgpass
          secret:
            secretName: mmts-metrics-pgpass
            optional: false
            defaultMode: 0600
        - name: hosts
          secret:
            optional: false
            secretName: mmts-metrics-hosts